[containers]

[engine]
  active_service = "podman_sock"
  [engine.service_destinations]
    [engine.service_destinations.podman_sock]
      uri = "unix:///home/frizzr/podman/podman.sock"

[machine]

[network]

[secrets]
